language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - git clone https://github.com/mozilla-services/switchboard-experiments
install: true
script: validate_and_sync_json.py travis_config.yaml
