language: python
python:
  - "2.7"
before_install:
  - git clone https://github.com/mozilla-services/switchboard-experiments
install: true
script:
  - python -m json.tool switchboard-experiments/*.json
